name: silentspeak
description: "A new Flutter project."
publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.3.4
  carousel_slider: ^4.0.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/1.jpeg
    - assets/images/2.jpeg
    - assets/images/3.jpeg
    - assets/images/4.jpeg
    - assets/images/5.jpeg
    - assets/images/6.jpeg
    - assets/images/7.jpeg
    - assets/images/8.jpeg
    - assets/images/9.jpg
    - assets/images/10.jpeg
    - assets/images/12.jpeg
    - assets/images/15.jpeg
    - assets/images/16.jpeg
    - assets/images/17.jpeg
    - assets/images/18.jpeg
    - assets/images/19.jpeg
    - assets/images/20.jpeg
    - assets/images/21.jpeg
    - assets/images/22.jpeg
    - assets/images/23.jpeg
    - assets/images/31.jpeg
    - assets/images/32.jpeg

